import glob
import json
import re
import sys


def normalize_url(raw_url: str | None) -> str:
    """Normalize URL to match markdown format (same as format_verify_url in update_ms_learn.py)."""
    if not raw_url or not isinstance(raw_url, str):
        return ""
    clean = raw_url.strip()
    # Remove trailing " program/" and any spaces that break URLs
    clean = re.sub(r'\s+program/?$', '', clean)
    clean = clean.replace(' ', '')
    if not clean:
        return ""
    # Handle learning path UID format: learn.viva-glint-360-feedback -> https://learn.microsoft.com/en-us/training/paths/viva-glint-360-feedback
    if clean.startswith("learn."):
        path_part = clean[6:]  # Remove "learn." prefix
        clean = f"https://learn.microsoft.com/en-us/training/paths/{path_part}"
    elif not clean.startswith("http"):
        if clean.startswith("/"):
            clean = f"https://learn.microsoft.com/en-us{clean}"
        else:
            clean = f"https://learn.microsoft.com/en-us/{clean}"
    elif "learn.microsoft.com/training/" in clean:
        clean = clean.replace("learn.microsoft.com/training/", "learn.microsoft.com/en-us/training/")
    return clean

retired = []
for f in glob.glob('for_validation/*.json'):
    try:
        with open(f, 'r', encoding='utf-8') as fp:
            data = json.load(fp)

        if isinstance(data, dict):
            if 'fingerprints' in data:
                continue
            items = []
            for key in ('badges', 'achievements', 'learning_paths', 'certifications', 'combined_feed', 'public_badges', 'detailed_learnings'):
                if key in data and isinstance(data[key], list):
                    items.extend(data[key])
            for key in ('verifiable_credentials', 'user_creds', 'userCredentials'):
                if key in data and isinstance(data[key], list):
                    items.extend(data[key])
            if not items:
                continue
        elif isinstance(data, list):
            items = data
        else:
            continue

        for item in items:
            if isinstance(item, dict) and item.get('retired'):
                # Try multiple URL fields
                url = None
                for field in ('url', 'learningPathUid', 'learning_path_uid', 'learningPathId', 'sourceUid'):
                    raw = item.get(field)
                    if raw:
                        url = normalize_url(raw)
                        if url:
                            break
                if url:
                    retired.append(url)
    except Exception as e:
        print(f'Warning: Could not parse {f}: {e}', file=sys.stderr)

if retired:
    # Write .lycheeignore file (recommended by lychee for permanent exclusions)
    with open('.lycheeignore', 'w', encoding='utf-8') as f:
        f.write('# Retired credentials - auto-generated by build_exclude.py\n')
        f.write('# These URLs return 404 and should be excluded from link checking\n\n')
        for url in retired:
            f.write(f'{url}\n')
    print('lycheeignore_written=true')
else:
    print('lycheeignore_written=false')