import glob
import json
import sys

retired = []
for f in glob.glob('for_validation/*.json'):
    try:
        with open(f, 'r', encoding='utf-8') as fp:
            data = json.load(fp)

        if isinstance(data, dict):
            if 'fingerprints' in data:
                continue
            items = []
            for key in ('badges', 'achievements', 'learning_paths', 'certifications', 'combined_feed', 'public_badges', 'detailed_learnings'):
                if key in data and isinstance(data[key], list):
                    items.extend(data[key])
            for key in ('verifiable_credentials', 'user_creds', 'userCredentials'):
                if key in data and isinstance(data[key], list):
                    items.extend(data[key])
            if not items:
                continue
        elif isinstance(data, list):
            items = data
        else:
            continue

        for item in items:
            if isinstance(item, dict) and item.get('retired') and item.get('url'):
                url = item['url']
                retired.append(url)
    except Exception as e:
        print(f'Warning: Could not parse {f}: {e}', file=sys.stderr)

if retired:
    # Write .lycheeignore file (recommended by lychee for permanent exclusions)
    with open('.lycheeignore', 'w', encoding='utf-8') as f:
        f.write('# Retired credentials - auto-generated by build_exclude.py\n')
        f.write('# These URLs return 404 and should be excluded from link checking\n\n')
        for url in retired:
            f.write(f'{url}\n')
    print('lycheeignore_written=true')
else:
    print('lycheeignore_written=false')